### ISSUE TITLE
`except ModuleNotFoundError or ImportError` not working

### ISSUE THREAD

**Issue by NicolasMICAUX** [SekouDiaoNlp/pylexique#104]
* pylexique version: 1.5.0
* Python version: 3.10
* Operating System: Ubuntu 22.04

### Description
`except ModuleNotFoundError or ImportError:` is incorrect syntax in `pylexique/pylexique.py`.

### What I Did
```
from pylexique import Lexique383
```
and I have a utils.py file in my project.

Getting error
```
     19 try:
---> 20     from utils import logger
     21 except ModuleNotFoundError or ImportError:
     22     from .utils import logger
ImportError: cannot import name 'logger' from 'utils' (/personal_path/utils.py)
```

**The correct `except` syntax seems to be `except (ModuleNotFoundError, ImportError):`.**

**Comment by SekouDiaoNlp** [comment]
Fixed with PR #105
