### ISSUE TITLE
How are accents handled?

### ISSUE THREAD

**Issue by NicolasMICAUX** [SekouDiaoNlp/pylexique#106]
* pylexique version: 1.5.0
* Python version: 3.10
* Operating System: ubuntu 22.04

### Description
Should handle accents when using the library, because it seems they were removed during pre-processing?
But this seems [not documented](https://pylexique.readthedocs.io/en/latest/search.html?q=accent&check_keywords=yes&area=default).

### What I Did
```bash
$ pylexique frère
[...]
KeyError: 'frère'
$ python
>>> [w for w in self.LEXIQUE.lexique if 'è' in w]
[]
>>> [w for w in self.LEXIQUE.lexique if w[:2] == 'fr' and w[-2:] == 're']
[...,
14: 'frre'  # I assume this is frère processed.
]
```

**Comment by SekouDiaoNlp** [comment]
Hi @NicolasMICAUX!

Thank you very much for opening the issue and letting me know about this odd behavior. I am in the process of investigating the issue and will keep you informed when I release the updated version of PyLexique very soon.

Cheers.
